/**
 * Country Master Seeder
 * Seeds all 195 countries with timezone, currency, and tax information
 */

const { HrmsCountryMaster } = require('../models/HrmsCountryMaster');
const { sequelize } = require('../utils/database');

const countries = [
    // A
    { country_name: 'Afghanistan', country_code: 'AF', iso_code_2: 'AF', iso_code_3: 'AFG', phone_code: '+93', abbreviation: 'AFG', primary_timezone: 'Asia/Kabul', utc_offset: '+4:30', currency: 'Afghan Afghani', currency_code: 'AFN', currency_symbol: '؋', sub_currency: 'Pul', service_tax: 0.00, is_active: true, display_order: 1 },
    { country_name: 'Albania', country_code: 'AL', iso_code_2: 'AL', iso_code_3: 'ALB', phone_code: '+355', abbreviation: 'ALB', primary_timezone: 'Europe/Tirane', utc_offset: '+1:00', currency: 'Albanian Lek', currency_code: 'ALL', currency_symbol: 'L', sub_currency: 'Qindarkë', service_tax: 20.00, is_active: true, display_order: 2 },
    { country_name: 'Algeria', country_code: 'DZ', iso_code_2: 'DZ', iso_code_3: 'DZA', phone_code: '+213', abbreviation: 'DZA', primary_timezone: 'Africa/Algiers', utc_offset: '+1:00', currency: 'Algerian Dinar', currency_code: 'DZD', currency_symbol: 'د.ج', sub_currency: 'Santeem', service_tax: 19.00, is_active: true, display_order: 3 },
    { country_name: 'Andorra', country_code: 'AD', iso_code_2: 'AD', iso_code_3: 'AND', phone_code: '+376', abbreviation: 'AND', primary_timezone: 'Europe/Andorra', utc_offset: '+1:00', currency: 'Euro', currency_code: 'EUR', currency_symbol: '€', sub_currency: 'Cent', service_tax: 4.50, is_active: true, display_order: 4 },
    { country_name: 'Angola', country_code: 'AO', iso_code_2: 'AO', iso_code_3: 'AGO', phone_code: '+244', abbreviation: 'AGO', primary_timezone: 'Africa/Luanda', utc_offset: '+1:00', currency: 'Angolan Kwanza', currency_code: 'AOA', currency_symbol: 'Kz', sub_currency: 'Cêntimo', service_tax: 14.00, is_active: true, display_order: 5 },
    { country_name: 'Antigua and Barbuda', country_code: 'AG', iso_code_2: 'AG', iso_code_3: 'ATG', phone_code: '+1-268', abbreviation: 'ATG', primary_timezone: 'America/Antigua', utc_offset: '-4:00', currency: 'East Caribbean Dollar', currency_code: 'XCD', currency_symbol: '$', sub_currency: 'Cent', service_tax: 15.00, is_active: true, display_order: 6 },
    { country_name: 'Argentina', country_code: 'AR', iso_code_2: 'AR', iso_code_3: 'ARG', phone_code: '+54', abbreviation: 'ARG', primary_timezone: 'America/Argentina/Buenos_Aires', utc_offset: '-3:00', currency: 'Argentine Peso', currency_code: 'ARS', currency_symbol: '$', sub_currency: 'Centavo', service_tax: 21.00, is_active: true, display_order: 7 },
    { country_name: 'Armenia', country_code: 'AM', iso_code_2: 'AM', iso_code_3: 'ARM', phone_code: '+374', abbreviation: 'ARM', primary_timezone: 'Asia/Yerevan', utc_offset: '+4:00', currency: 'Armenian Dram', currency_code: 'AMD', currency_symbol: '֏', sub_currency: 'Luma', service_tax: 20.00, is_active: true, display_order: 8 },
    { country_name: 'Australia', country_code: 'AU', iso_code_2: 'AU', iso_code_3: 'AUS', phone_code: '+61', abbreviation: 'AUS', primary_timezone: 'Australia/Sydney', utc_offset: '+10:00', currency: 'Australian Dollar', currency_code: 'AUD', currency_symbol: 'A$', sub_currency: 'Cent', service_tax: 10.00, is_active: true, display_order: 9 },
    { country_name: 'Austria', country_code: 'AT', iso_code_2: 'AT', iso_code_3: 'AUT', phone_code: '+43', abbreviation: 'AUT', primary_timezone: 'Europe/Vienna', utc_offset: '+1:00', currency: 'Euro', currency_code: 'EUR', currency_symbol: '€', sub_currency: 'Cent', service_tax: 20.00, is_active: true, display_order: 10 },
    { country_name: 'Azerbaijan', country_code: 'AZ', iso_code_2: 'AZ', iso_code_3: 'AZE', phone_code: '+994', abbreviation: 'AZE', primary_timezone: 'Asia/Baku', utc_offset: '+4:00', currency: 'Azerbaijani Manat', currency_code: 'AZN', currency_symbol: '₼', sub_currency: 'Qəpik', service_tax: 18.00, is_active: true, display_order: 11 },

    // B
    { country_name: 'Bahamas', country_code: 'BS', iso_code_2: 'BS', iso_code_3: 'BHS', phone_code: '+1-242', abbreviation: 'BHS', primary_timezone: 'America/Nassau', utc_offset: '-5:00', currency: 'Bahamian Dollar', currency_code: 'BSD', currency_symbol: '$', sub_currency: 'Cent', service_tax: 12.00, is_active: true, display_order: 12 },
    { country_name: 'Bahrain', country_code: 'BH', iso_code_2: 'BH', iso_code_3: 'BHR', phone_code: '+973', abbreviation: 'BHR', primary_timezone: 'Asia/Bahrain', utc_offset: '+3:00', currency: 'Bahraini Dinar', currency_code: 'BHD', currency_symbol: '.د.ب', sub_currency: 'Fils', service_tax: 10.00, is_active: true, display_order: 13 },
    { country_name: 'Bangladesh', country_code: 'BD', iso_code_2: 'BD', iso_code_3: 'BGD', phone_code: '+880', abbreviation: 'BGD', primary_timezone: 'Asia/Dhaka', utc_offset: '+6:00', currency: 'Bangladeshi Taka', currency_code: 'BDT', currency_symbol: '৳', sub_currency: 'Paisa', service_tax: 15.00, is_active: true, display_order: 14 },
    { country_name: 'Barbados', country_code: 'BB', iso_code_2: 'BB', iso_code_3: 'BRB', phone_code: '+1-246', abbreviation: 'BRB', primary_timezone: 'America/Barbados', utc_offset: '-4:00', currency: 'Barbadian Dollar', currency_code: 'BBD', currency_symbol: '$', sub_currency: 'Cent', service_tax: 17.50, is_active: true, display_order: 15 },
    { country_name: 'Belarus', country_code: 'BY', iso_code_2: 'BY', iso_code_3: 'BLR', phone_code: '+375', abbreviation: 'BLR', primary_timezone: 'Europe/Minsk', utc_offset: '+3:00', currency: 'Belarusian Ruble', currency_code: 'BYN', currency_symbol: 'Br', sub_currency: 'Kapyeyka', service_tax: 20.00, is_active: true, display_order: 16 },
    { country_name: 'Belgium', country_code: 'BE', iso_code_2: 'BE', iso_code_3: 'BEL', phone_code: '+32', abbreviation: 'BEL', primary_timezone: 'Europe/Brussels', utc_offset: '+1:00', currency: 'Euro', currency_code: 'EUR', currency_symbol: '€', sub_currency: 'Cent', service_tax: 21.00, is_active: true, display_order: 17 },
    { country_name: 'Belize', country_code: 'BZ', iso_code_2: 'BZ', iso_code_3: 'BLZ', phone_code: '+501', abbreviation: 'BLZ', primary_timezone: 'America/Belize', utc_offset: '-6:00', currency: 'Belize Dollar', currency_code: 'BZD', currency_symbol: '$', sub_currency: 'Cent', service_tax: 12.50, is_active: true, display_order: 18 },
    { country_name: 'Benin', country_code: 'BJ', iso_code_2: 'BJ', iso_code_3: 'BEN', phone_code: '+229', abbreviation: 'BEN', primary_timezone: 'Africa/Porto-Novo', utc_offset: '+1:00', currency: 'West African CFA Franc', currency_code: 'XOF', currency_symbol: 'Fr', sub_currency: 'Centime', service_tax: 18.00, is_active: true, display_order: 19 },
    { country_name: 'Bhutan', country_code: 'BT', iso_code_2: 'BT', iso_code_3: 'BTN', phone_code: '+975', abbreviation: 'BTN', primary_timezone: 'Asia/Thimphu', utc_offset: '+6:00', currency: 'Bhutanese Ngultrum', currency_code: 'BTN', currency_symbol: 'Nu.', sub_currency: 'Chetrum', service_tax: 0.00, is_active: true, display_order: 20 },
    { country_name: 'Bolivia', country_code: 'BO', iso_code_2: 'BO', iso_code_3: 'BOL', phone_code: '+591', abbreviation: 'BOL', primary_timezone: 'America/La_Paz', utc_offset: '-4:00', currency: 'Bolivian Boliviano', currency_code: 'BOB', currency_symbol: 'Bs.', sub_currency: 'Centavo', service_tax: 13.00, is_active: true, display_order: 21 },
    { country_name: 'Bosnia and Herzegovina', country_code: 'BA', iso_code_2: 'BA', iso_code_3: 'BIH', phone_code: '+387', abbreviation: 'BIH', primary_timezone: 'Europe/Sarajevo', utc_offset: '+1:00', currency: 'Bosnia-Herzegovina Convertible Mark', currency_code: 'BAM', currency_symbol: 'KM', sub_currency: 'Fening', service_tax: 17.00, is_active: true, display_order: 22 },
    { country_name: 'Botswana', country_code: 'BW', iso_code_2: 'BW', iso_code_3: 'BWA', phone_code: '+267', abbreviation: 'BWA', primary_timezone: 'Africa/Gaborone', utc_offset: '+2:00', currency: 'Botswana Pula', currency_code: 'BWP', currency_symbol: 'P', sub_currency: 'Thebe', service_tax: 14.00, is_active: true, display_order: 23 },
    { country_name: 'Brazil', country_code: 'BR', iso_code_2: 'BR', iso_code_3: 'BRA', phone_code: '+55', abbreviation: 'BRA', primary_timezone: 'America/Sao_Paulo', utc_offset: '-3:00', currency: 'Brazilian Real', currency_code: 'BRL', currency_symbol: 'R$', sub_currency: 'Centavo', service_tax: 0.00, is_active: true, display_order: 24 },
    { country_name: 'Brunei', country_code: 'BN', iso_code_2: 'BN', iso_code_3: 'BRN', phone_code: '+673', abbreviation: 'BRN', primary_timezone: 'Asia/Brunei', utc_offset: '+8:00', currency: 'Brunei Dollar', currency_code: 'BND', currency_symbol: '$', sub_currency: 'Sen', service_tax: 0.00, is_active: true, display_order: 25 },
    { country_name: 'Bulgaria', country_code: 'BG', iso_code_2: 'BG', iso_code_3: 'BGR', phone_code: '+359', abbreviation: 'BGR', primary_timezone: 'Europe/Sofia', utc_offset: '+2:00', currency: 'Bulgarian Lev', currency_code: 'BGN', currency_symbol: 'лв', sub_currency: 'Stotinka', service_tax: 20.00, is_active: true, display_order: 26 },
    { country_name: 'Burkina Faso', country_code: 'BF', iso_code_2: 'BF', iso_code_3: 'BFA', phone_code: '+226', abbreviation: 'BFA', primary_timezone: 'Africa/Ouagadougou', utc_offset: '+0:00', currency: 'West African CFA Franc', currency_code: 'XOF', currency_symbol: 'Fr', sub_currency: 'Centime', service_tax: 18.00, is_active: true, display_order: 27 },
    { country_name: 'Burundi', country_code: 'BI', iso_code_2: 'BI', iso_code_3: 'BDI', phone_code: '+257', abbreviation: 'BDI', primary_timezone: 'Africa/Bujumbura', utc_offset: '+2:00', currency: 'Burundian Franc', currency_code: 'BIF', currency_symbol: 'Fr', sub_currency: 'Centime', service_tax: 18.00, is_active: true, display_order: 28 },

    // C
    { country_name: 'Cambodia', country_code: 'KH', iso_code_2: 'KH', iso_code_3: 'KHM', phone_code: '+855', abbreviation: 'KHM', primary_timezone: 'Asia/Phnom_Penh', utc_offset: '+7:00', currency: 'Cambodian Riel', currency_code: 'KHR', currency_symbol: '៛', sub_currency: 'Sen', service_tax: 10.00, is_active: true, display_order: 29 },
    { country_name: 'Cameroon', country_code: 'CM', iso_code_2: 'CM', iso_code_3: 'CMR', phone_code: '+237', abbreviation: 'CMR', primary_timezone: 'Africa/Douala', utc_offset: '+1:00', currency: 'Central African CFA Franc', currency_code: 'XAF', currency_symbol: 'Fr', sub_currency: 'Centime', service_tax: 19.25, is_active: true, display_order: 30 },
    { country_name: 'Canada', country_code: 'CA', iso_code_2: 'CA', iso_code_3: 'CAN', phone_code: '+1', abbreviation: 'CAN', primary_timezone: 'America/Toronto', utc_offset: '-5:00', currency: 'Canadian Dollar', currency_code: 'CAD', currency_symbol: 'C$', sub_currency: 'Cent', service_tax: 5.00, is_active: true, display_order: 31 },
    { country_name: 'Cape Verde', country_code: 'CV', iso_code_2: 'CV', iso_code_3: 'CPV', phone_code: '+238', abbreviation: 'CPV', primary_timezone: 'Atlantic/Cape_Verde', utc_offset: '-1:00', currency: 'Cape Verdean Escudo', currency_code: 'CVE', currency_symbol: '$', sub_currency: 'Centavo', service_tax: 15.00, is_active: true, display_order: 32 },
    { country_name: 'Central African Republic', country_code: 'CF', iso_code_2: 'CF', iso_code_3: 'CAF', phone_code: '+236', abbreviation: 'CAF', primary_timezone: 'Africa/Bangui', utc_offset: '+1:00', currency: 'Central African CFA Franc', currency_code: 'XAF', currency_symbol: 'Fr', sub_currency: 'Centime', service_tax: 19.00, is_active: true, display_order: 33 },
    { country_name: 'Chad', country_code: 'TD', iso_code_2: 'TD', iso_code_3: 'TCD', phone_code: '+235', abbreviation: 'TCD', primary_timezone: 'Africa/Ndjamena', utc_offset: '+1:00', currency: 'Central African CFA Franc', currency_code: 'XAF', currency_symbol: 'Fr', sub_currency: 'Centime', service_tax: 18.00, is_active: true, display_order: 34 },
    { country_name: 'Chile', country_code: 'CL', iso_code_2: 'CL', iso_code_3: 'CHL', phone_code: '+56', abbreviation: 'CHL', primary_timezone: 'America/Santiago', utc_offset: '-3:00', currency: 'Chilean Peso', currency_code: 'CLP', currency_symbol: '$', sub_currency: 'Centavo', service_tax: 19.00, is_active: true, display_order: 35 },
    { country_name: 'China', country_code: 'CN', iso_code_2: 'CN', iso_code_3: 'CHN', phone_code: '+86', abbreviation: 'CHN', primary_timezone: 'Asia/Shanghai', utc_offset: '+8:00', currency: 'Chinese Yuan', currency_code: 'CNY', currency_symbol: '¥', sub_currency: 'Fen', service_tax: 6.00, is_active: true, display_order: 36 },
    { country_name: 'Colombia', country_code: 'CO', iso_code_2: 'CO', iso_code_3: 'COL', phone_code: '+57', abbreviation: 'COL', primary_timezone: 'America/Bogota', utc_offset: '-5:00', currency: 'Colombian Peso', currency_code: 'COP', currency_symbol: '$', sub_currency: 'Centavo', service_tax: 19.00, is_active: true, display_order: 37 },
    { country_name: 'Comoros', country_code: 'KM', iso_code_2: 'KM', iso_code_3: 'COM', phone_code: '+269', abbreviation: 'COM', primary_timezone: 'Indian/Comoro', utc_offset: '+3:00', currency: 'Comorian Franc', currency_code: 'KMF', currency_symbol: 'Fr', sub_currency: 'Centime', service_tax: 10.00, is_active: true, display_order: 38 },
    { country_name: 'Congo', country_code: 'CG', iso_code_2: 'CG', iso_code_3: 'COG', phone_code: '+242', abbreviation: 'COG', primary_timezone: 'Africa/Brazzaville', utc_offset: '+1:00', currency: 'Central African CFA Franc', currency_code: 'XAF', currency_symbol: 'Fr', sub_currency: 'Centime', service_tax: 18.00, is_active: true, display_order: 39 },
    { country_name: 'Costa Rica', country_code: 'CR', iso_code_2: 'CR', iso_code_3: 'CRI', phone_code: '+506', abbreviation: 'CRI', primary_timezone: 'America/Costa_Rica', utc_offset: '-6:00', currency: 'Costa Rican Colón', currency_code: 'CRC', currency_symbol: '₡', sub_currency: 'Céntimo', service_tax: 13.00, is_active: true, display_order: 40 },
    { country_name: 'Croatia', country_code: 'HR', iso_code_2: 'HR', iso_code_3: 'HRV', phone_code: '+385', abbreviation: 'HRV', primary_timezone: 'Europe/Zagreb', utc_offset: '+1:00', currency: 'Euro', currency_code: 'EUR', currency_symbol: '€', sub_currency: 'Cent', service_tax: 25.00, is_active: true, display_order: 41 },
    { country_name: 'Cuba', country_code: 'CU', iso_code_2: 'CU', iso_code_3: 'CUB', phone_code: '+53', abbreviation: 'CUB', primary_timezone: 'America/Havana', utc_offset: '-5:00', currency: 'Cuban Peso', currency_code: 'CUP', currency_symbol: '$', sub_currency: 'Centavo', service_tax: 0.00, is_active: true, display_order: 42 },
    { country_name: 'Cyprus', country_code: 'CY', iso_code_2: 'CY', iso_code_3: 'CYP', phone_code: '+357', abbreviation: 'CYP', primary_timezone: 'Asia/Nicosia', utc_offset: '+2:00', currency: 'Euro', currency_code: 'EUR', currency_symbol: '€', sub_currency: 'Cent', service_tax: 19.00, is_active: true, display_order: 43 },
    { country_name: 'Czech Republic', country_code: 'CZ', iso_code_2: 'CZ', iso_code_3: 'CZE', phone_code: '+420', abbreviation: 'CZE', primary_timezone: 'Europe/Prague', utc_offset: '+1:00', currency: 'Czech Koruna', currency_code: 'CZK', currency_symbol: 'Kč', sub_currency: 'Haléř', service_tax: 21.00, is_active: true, display_order: 44 },

    // D
    { country_name: 'Democratic Republic of the Congo', country_code: 'CD', iso_code_2: 'CD', iso_code_3: 'COD', phone_code: '+243', abbreviation: 'COD', primary_timezone: 'Africa/Kinshasa', utc_offset: '+1:00', currency: 'Congolese Franc', currency_code: 'CDF', currency_symbol: 'Fr', sub_currency: 'Centime', service_tax: 16.00, is_active: true, display_order: 45 },
    { country_name: 'Denmark', country_code: 'DK', iso_code_2: 'DK', iso_code_3: 'DNK', phone_code: '+45', abbreviation: 'DNK', primary_timezone: 'Europe/Copenhagen', utc_offset: '+1:00', currency: 'Danish Krone', currency_code: 'DKK', currency_symbol: 'kr', sub_currency: 'Øre', service_tax: 25.00, is_active: true, display_order: 46 },
    { country_name: 'Djibouti', country_code: 'DJ', iso_code_2: 'DJ', iso_code_3: 'DJI', phone_code: '+253', abbreviation: 'DJI', primary_timezone: 'Africa/Djibouti', utc_offset: '+3:00', currency: 'Djiboutian Franc', currency_code: 'DJF', currency_symbol: 'Fr', sub_currency: 'Centime', service_tax: 10.00, is_active: true, display_order: 47 },
    { country_name: 'Dominica', country_code: 'DM', iso_code_2: 'DM', iso_code_3: 'DMA', phone_code: '+1-767', abbreviation: 'DMA', primary_timezone: 'America/Dominica', utc_offset: '-4:00', currency: 'East Caribbean Dollar', currency_code: 'XCD', currency_symbol: '$', sub_currency: 'Cent', service_tax: 15.00, is_active: true, display_order: 48 },
    { country_name: 'Dominican Republic', country_code: 'DO', iso_code_2: 'DO', iso_code_3: 'DOM', phone_code: '+1-809', abbreviation: 'DOM', primary_timezone: 'America/Santo_Domingo', utc_offset: '-4:00', currency: 'Dominican Peso', currency_code: 'DOP', currency_symbol: '$', sub_currency: 'Centavo', service_tax: 18.00, is_active: true, display_order: 49 },

    // E
    { country_name: 'East Timor', country_code: 'TL', iso_code_2: 'TL', iso_code_3: 'TLS', phone_code: '+670', abbreviation: 'TLS', primary_timezone: 'Asia/Dili', utc_offset: '+9:00', currency: 'United States Dollar', currency_code: 'USD', currency_symbol: '$', sub_currency: 'Cent', service_tax: 0.00, is_active: true, display_order: 50 },
    { country_name: 'Ecuador', country_code: 'EC', iso_code_2: 'EC', iso_code_3: 'ECU', phone_code: '+593', abbreviation: 'ECU', primary_timezone: 'America/Guayaquil', utc_offset: '-5:00', currency: 'United States Dollar', currency_code: 'USD', currency_symbol: '$', sub_currency: 'Cent', service_tax: 12.00, is_active: true, display_order: 51 },
    { country_name: 'Egypt', country_code: 'EG', iso_code_2: 'EG', iso_code_3: 'EGY', phone_code: '+20', abbreviation: 'EGY', primary_timezone: 'Africa/Cairo', utc_offset: '+2:00', currency: 'Egyptian Pound', currency_code: 'EGP', currency_symbol: 'E£', sub_currency: 'Piastre', service_tax: 14.00, is_active: true, display_order: 52 },
    { country_name: 'El Salvador', country_code: 'SV', iso_code_2: 'SV', iso_code_3: 'SLV', phone_code: '+503', abbreviation: 'SLV', primary_timezone: 'America/El_Salvador', utc_offset: '-6:00', currency: 'United States Dollar', currency_code: 'USD', currency_symbol: '$', sub_currency: 'Cent', service_tax: 13.00, is_active: true, display_order: 53 },
    { country_name: 'Equatorial Guinea', country_code: 'GQ', iso_code_2: 'GQ', iso_code_3: 'GNQ', phone_code: '+240', abbreviation: 'GNQ', primary_timezone: 'Africa/Malabo', utc_offset: '+1:00', currency: 'Central African CFA Franc', currency_code: 'XAF', currency_symbol: 'Fr', sub_currency: 'Centime', service_tax: 15.00, is_active: true, display_order: 54 },
    { country_name: 'Eritrea', country_code: 'ER', iso_code_2: 'ER', iso_code_3: 'ERI', phone_code: '+291', abbreviation: 'ERI', primary_timezone: 'Africa/Asmara', utc_offset: '+3:00', currency: 'Eritrean Nakfa', currency_code: 'ERN', currency_symbol: 'Nfk', sub_currency: 'Cent', service_tax: 5.00, is_active: true, display_order: 55 },
    { country_name: 'Estonia', country_code: 'EE', iso_code_2: 'EE', iso_code_3: 'EST', phone_code: '+372', abbreviation: 'EST', primary_timezone: 'Europe/Tallinn', utc_offset: '+2:00', currency: 'Euro', currency_code: 'EUR', currency_symbol: '€', sub_currency: 'Cent', service_tax: 20.00, is_active: true, display_order: 56 },
    { country_name: 'Eswatini', country_code: 'SZ', iso_code_2: 'SZ', iso_code_3: 'SWZ', phone_code: '+268', abbreviation: 'SWZ', primary_timezone: 'Africa/Mbabane', utc_offset: '+2:00', currency: 'Swazi Lilangeni', currency_code: 'SZL', currency_symbol: 'L', sub_currency: 'Cent', service_tax: 15.00, is_active: true, display_order: 57 },
    { country_name: 'Ethiopia', country_code: 'ET', iso_code_2: 'ET', iso_code_3: 'ETH', phone_code: '+251', abbreviation: 'ETH', primary_timezone: 'Africa/Addis_Ababa', utc_offset: '+3:00', currency: 'Ethiopian Birr', currency_code: 'ETB', currency_symbol: 'Br', sub_currency: 'Santim', service_tax: 15.00, is_active: true, display_order: 58 },

    // F
    { country_name: 'Fiji', country_code: 'FJ', iso_code_2: 'FJ', iso_code_3: 'FJI', phone_code: '+679', abbreviation: 'FJI', primary_timezone: 'Pacific/Fiji', utc_offset: '+12:00', currency: 'Fijian Dollar', currency_code: 'FJD', currency_symbol: '$', sub_currency: 'Cent', service_tax: 9.00, is_active: true, display_order: 59 },
    { country_name: 'Finland', country_code: 'FI', iso_code_2: 'FI', iso_code_3: 'FIN', phone_code: '+358', abbreviation: 'FIN', primary_timezone: 'Europe/Helsinki', utc_offset: '+2:00', currency: 'Euro', currency_code: 'EUR', currency_symbol: '€', sub_currency: 'Cent', service_tax: 24.00, is_active: true, display_order: 60 },
    { country_name: 'France', country_code: 'FR', iso_code_2: 'FR', iso_code_3: 'FRA', phone_code: '+33', abbreviation: 'FRA', primary_timezone: 'Europe/Paris', utc_offset: '+1:00', currency: 'Euro', currency_code: 'EUR', currency_symbol: '€', sub_currency: 'Cent', service_tax: 20.00, is_active: true, display_order: 61 },

    // G
    { country_name: 'Gabon', country_code: 'GA', iso_code_2: 'GA', iso_code_3: 'GAB', phone_code: '+241', abbreviation: 'GAB', primary_timezone: 'Africa/Libreville', utc_offset: '+1:00', currency: 'Central African CFA Franc', currency_code: 'XAF', currency_symbol: 'Fr', sub_currency: 'Centime', service_tax: 18.00, is_active: true, display_order: 62 },
    { country_name: 'Gambia', country_code: 'GM', iso_code_2: 'GM', iso_code_3: 'GMB', phone_code: '+220', abbreviation: 'GMB', primary_timezone: 'Africa/Banjul', utc_offset: '+0:00', currency: 'Gambian Dalasi', currency_code: 'GMD', currency_symbol: 'D', sub_currency: 'Butut', service_tax: 15.00, is_active: true, display_order: 63 },
    { country_name: 'Georgia', country_code: 'GE', iso_code_2: 'GE', iso_code_3: 'GEO', phone_code: '+995', abbreviation: 'GEO', primary_timezone: 'Asia/Tbilisi', utc_offset: '+4:00', currency: 'Georgian Lari', currency_code: 'GEL', currency_symbol: '₾', sub_currency: 'Tetri', service_tax: 18.00, is_active: true, display_order: 64 },
    { country_name: 'Germany', country_code: 'DE', iso_code_2: 'DE', iso_code_3: 'DEU', phone_code: '+49', abbreviation: 'GER', primary_timezone: 'Europe/Berlin', utc_offset: '+1:00', currency: 'Euro', currency_code: 'EUR', currency_symbol: '€', sub_currency: 'Cent', service_tax: 19.00, is_active: true, display_order: 65 },
    { country_name: 'Ghana', country_code: 'GH', iso_code_2: 'GH', iso_code_3: 'GHA', phone_code: '+233', abbreviation: 'GHA', primary_timezone: 'Africa/Accra', utc_offset: '+0:00', currency: 'Ghanaian Cedi', currency_code: 'GHS', currency_symbol: '₵', sub_currency: 'Pesewa', service_tax: 12.50, is_active: true, display_order: 66 },
    { country_name: 'Greece', country_code: 'GR', iso_code_2: 'GR', iso_code_3: 'GRC', phone_code: '+30', abbreviation: 'GRC', primary_timezone: 'Europe/Athens', utc_offset: '+2:00', currency: 'Euro', currency_code: 'EUR', currency_symbol: '€', sub_currency: 'Cent', service_tax: 24.00, is_active: true, display_order: 67 },
    { country_name: 'Grenada', country_code: 'GD', iso_code_2: 'GD', iso_code_3: 'GRD', phone_code: '+1-473', abbreviation: 'GRD', primary_timezone: 'America/Grenada', utc_offset: '-4:00', currency: 'East Caribbean Dollar', currency_code: 'XCD', currency_symbol: '$', sub_currency: 'Cent', service_tax: 15.00, is_active: true, display_order: 68 },
    { country_name: 'Guatemala', country_code: 'GT', iso_code_2: 'GT', iso_code_3: 'GTM', phone_code: '+502', abbreviation: 'GTM', primary_timezone: 'America/Guatemala', utc_offset: '-6:00', currency: 'Guatemalan Quetzal', currency_code: 'GTQ', currency_symbol: 'Q', sub_currency: 'Centavo', service_tax: 12.00, is_active: true, display_order: 69 },
    { country_name: 'Guinea', country_code: 'GN', iso_code_2: 'GN', iso_code_3: 'GIN', phone_code: '+224', abbreviation: 'GIN', primary_timezone: 'Africa/Conakry', utc_offset: '+0:00', currency: 'Guinean Franc', currency_code: 'GNF', currency_symbol: 'Fr', sub_currency: 'Centime', service_tax: 18.00, is_active: true, display_order: 70 },
    { country_name: 'Guinea-Bissau', country_code: 'GW', iso_code_2: 'GW', iso_code_3: 'GNB', phone_code: '+245', abbreviation: 'GNB', primary_timezone: 'Africa/Bissau', utc_offset: '+0:00', currency: 'West African CFA Franc', currency_code: 'XOF', currency_symbol: 'Fr', sub_currency: 'Centime', service_tax: 15.00, is_active: true, display_order: 71 },
    { country_name: 'Guyana', country_code: 'GY', iso_code_2: 'GY', iso_code_3: 'GUY', phone_code: '+592', abbreviation: 'GUY', primary_timezone: 'America/Guyana', utc_offset: '-4:00', currency: 'Guyanese Dollar', currency_code: 'GYD', currency_symbol: '$', sub_currency: 'Cent', service_tax: 14.00, is_active: true, display_order: 72 },

    // H
    { country_name: 'Haiti', country_code: 'HT', iso_code_2: 'HT', iso_code_3: 'HTI', phone_code: '+509', abbreviation: 'HTI', primary_timezone: 'America/Port-au-Prince', utc_offset: '-5:00', currency: 'Haitian Gourde', currency_code: 'HTG', currency_symbol: 'G', sub_currency: 'Centime', service_tax: 10.00, is_active: true, display_order: 73 },
    { country_name: 'Honduras', country_code: 'HN', iso_code_2: 'HN', iso_code_3: 'HND', phone_code: '+504', abbreviation: 'HND', primary_timezone: 'America/Tegucigalpa', utc_offset: '-6:00', currency: 'Honduran Lempira', currency_code: 'HNL', currency_symbol: 'L', sub_currency: 'Centavo', service_tax: 15.00, is_active: true, display_order: 74 },
    { country_name: 'Hungary', country_code: 'HU', iso_code_2: 'HU', iso_code_3: 'HUN', phone_code: '+36', abbreviation: 'HUN', primary_timezone: 'Europe/Budapest', utc_offset: '+1:00', currency: 'Hungarian Forint', currency_code: 'HUF', currency_symbol: 'Ft', sub_currency: 'Fillér', service_tax: 27.00, is_active: true, display_order: 75 },

    // I
    { country_name: 'Iceland', country_code: 'IS', iso_code_2: 'IS', iso_code_3: 'ISL', phone_code: '+354', abbreviation: 'ISL', primary_timezone: 'Atlantic/Reykjavik', utc_offset: '+0:00', currency: 'Icelandic Króna', currency_code: 'ISK', currency_symbol: 'kr', sub_currency: 'Eyrir', service_tax: 24.00, is_active: true, display_order: 76 },
    { country_name: 'India', country_code: 'IN', iso_code_2: 'IN', iso_code_3: 'IND', phone_code: '+91', abbreviation: 'IND', primary_timezone: 'Asia/Kolkata', utc_offset: '+5:30', currency: 'Indian Rupee', currency_code: 'INR', currency_symbol: '₹', sub_currency: 'Paisa', service_tax: 18.00, is_active: true, display_order: 77 },
    { country_name: 'Indonesia', country_code: 'ID', iso_code_2: 'ID', iso_code_3: 'IDN', phone_code: '+62', abbreviation: 'IDN', primary_timezone: 'Asia/Jakarta', utc_offset: '+7:00', currency: 'Indonesian Rupiah', currency_code: 'IDR', currency_symbol: 'Rp', sub_currency: 'Sen', service_tax: 11.00, is_active: true, display_order: 78 },
    { country_name: 'Iran', country_code: 'IR', iso_code_2: 'IR', iso_code_3: 'IRN', phone_code: '+98', abbreviation: 'IRN', primary_timezone: 'Asia/Tehran', utc_offset: '+3:30', currency: 'Iranian Rial', currency_code: 'IRR', currency_symbol: '﷼', sub_currency: 'Dinar', service_tax: 9.00, is_active: true, display_order: 79 },
    { country_name: 'Iraq', country_code: 'IQ', iso_code_2: 'IQ', iso_code_3: 'IRQ', phone_code: '+964', abbreviation: 'IRQ', primary_timezone: 'Asia/Baghdad', utc_offset: '+3:00', currency: 'Iraqi Dinar', currency_code: 'IQD', currency_symbol: 'ع.د', sub_currency: 'Fils', service_tax: 0.00, is_active: true, display_order: 80 },
    { country_name: 'Ireland', country_code: 'IE', iso_code_2: 'IE', iso_code_3: 'IRL', phone_code: '+353', abbreviation: 'IRL', primary_timezone: 'Europe/Dublin', utc_offset: '+0:00', currency: 'Euro', currency_code: 'EUR', currency_symbol: '€', sub_currency: 'Cent', service_tax: 23.00, is_active: true, display_order: 81 },
    { country_name: 'Israel', country_code: 'IL', iso_code_2: 'IL', iso_code_3: 'ISR', phone_code: '+972', abbreviation: 'ISR', primary_timezone: 'Asia/Jerusalem', utc_offset: '+2:00', currency: 'Israeli New Shekel', currency_code: 'ILS', currency_symbol: '₪', sub_currency: 'Agora', service_tax: 17.00, is_active: true, display_order: 82 },
    { country_name: 'Italy', country_code: 'IT', iso_code_2: 'IT', iso_code_3: 'ITA', phone_code: '+39', abbreviation: 'ITA', primary_timezone: 'Europe/Rome', utc_offset: '+1:00', currency: 'Euro', currency_code: 'EUR', currency_symbol: '€', sub_currency: 'Cent', service_tax: 22.00, is_active: true, display_order: 83 },
    { country_name: 'Ivory Coast', country_code: 'CI', iso_code_2: 'CI', iso_code_3: 'CIV', phone_code: '+225', abbreviation: 'CIV', primary_timezone: 'Africa/Abidjan', utc_offset: '+0:00', currency: 'West African CFA Franc', currency_code: 'XOF', currency_symbol: 'Fr', sub_currency: 'Centime', service_tax: 18.00, is_active: true, display_order: 84 },

    // J
    { country_name: 'Jamaica', country_code: 'JM', iso_code_2: 'JM', iso_code_3: 'JAM', phone_code: '+1-876', abbreviation: 'JAM', primary_timezone: 'America/Jamaica', utc_offset: '-5:00', currency: 'Jamaican Dollar', currency_code: 'JMD', currency_symbol: '$', sub_currency: 'Cent', service_tax: 15.00, is_active: true, display_order: 85 },
    { country_name: 'Japan', country_code: 'JP', iso_code_2: 'JP', iso_code_3: 'JPN', phone_code: '+81', abbreviation: 'JPN', primary_timezone: 'Asia/Tokyo', utc_offset: '+9:00', currency: 'Japanese Yen', currency_code: 'JPY', currency_symbol: '¥', sub_currency: 'Sen', service_tax: 10.00, is_active: true, display_order: 86 },
    { country_name: 'Jordan', country_code: 'JO', iso_code_2: 'JO', iso_code_3: 'JOR', phone_code: '+962', abbreviation: 'JOR', primary_timezone: 'Asia/Amman', utc_offset: '+2:00', currency: 'Jordanian Dinar', currency_code: 'JOD', currency_symbol: 'د.ا', sub_currency: 'Piastre', service_tax: 16.00, is_active: true, display_order: 87 },

    // K
    { country_name: 'Kazakhstan', country_code: 'KZ', iso_code_2: 'KZ', iso_code_3: 'KAZ', phone_code: '+7', abbreviation: 'KAZ', primary_timezone: 'Asia/Almaty', utc_offset: '+6:00', currency: 'Kazakhstani Tenge', currency_code: 'KZT', currency_symbol: '₸', sub_currency: 'Tıyn', service_tax: 12.00, is_active: true, display_order: 88 },
    { country_name: 'Kenya', country_code: 'KE', iso_code_2: 'KE', iso_code_3: 'KEN', phone_code: '+254', abbreviation: 'KEN', primary_timezone: 'Africa/Nairobi', utc_offset: '+3:00', currency: 'Kenyan Shilling', currency_code: 'KES', currency_symbol: 'Sh', sub_currency: 'Cent', service_tax: 16.00, is_active: true, display_order: 89 },
    { country_name: 'Kiribati', country_code: 'KI', iso_code_2: 'KI', iso_code_3: 'KIR', phone_code: '+686', abbreviation: 'KIR', primary_timezone: 'Pacific/Tarawa', utc_offset: '+12:00', currency: 'Australian Dollar', currency_code: 'AUD', currency_symbol: '$', sub_currency: 'Cent', service_tax: 0.00, is_active: true, display_order: 90 },
    { country_name: 'Kuwait', country_code: 'KW', iso_code_2: 'KW', iso_code_3: 'KWT', phone_code: '+965', abbreviation: 'KWT', primary_timezone: 'Asia/Kuwait', utc_offset: '+3:00', currency: 'Kuwaiti Dinar', currency_code: 'KWD', currency_symbol: 'د.ك', sub_currency: 'Fils', service_tax: 0.00, is_active: true, display_order: 91 },
    { country_name: 'Kyrgyzstan', country_code: 'KG', iso_code_2: 'KG', iso_code_3: 'KGZ', phone_code: '+996', abbreviation: 'KGZ', primary_timezone: 'Asia/Bishkek', utc_offset: '+6:00', currency: 'Kyrgyzstani Som', currency_code: 'KGS', currency_symbol: 'с', sub_currency: 'Tyiyn', service_tax: 12.00, is_active: true, display_order: 92 },

    // L
    { country_name: 'Laos', country_code: 'LA', iso_code_2: 'LA', iso_code_3: 'LAO', phone_code: '+856', abbreviation: 'LAO', primary_timezone: 'Asia/Vientiane', utc_offset: '+7:00', currency: 'Lao Kip', currency_code: 'LAK', currency_symbol: '₭', sub_currency: 'Att', service_tax: 10.00, is_active: true, display_order: 93 },
    { country_name: 'Latvia', country_code: 'LV', iso_code_2: 'LV', iso_code_3: 'LVA', phone_code: '+371', abbreviation: 'LVA', primary_timezone: 'Europe/Riga', utc_offset: '+2:00', currency: 'Euro', currency_code: 'EUR', currency_symbol: '€', sub_currency: 'Cent', service_tax: 21.00, is_active: true, display_order: 94 },
    { country_name: 'Lebanon', country_code: 'LB', iso_code_2: 'LB', iso_code_3: 'LBN', phone_code: '+961', abbreviation: 'LBN', primary_timezone: 'Asia/Beirut', utc_offset: '+2:00', currency: 'Lebanese Pound', currency_code: 'LBP', currency_symbol: 'ل.ل', sub_currency: 'Piastre', service_tax: 11.00, is_active: true, display_order: 95 },
    { country_name: 'Lesotho', country_code: 'LS', iso_code_2: 'LS', iso_code_3: 'LSO', phone_code: '+266', abbreviation: 'LSO', primary_timezone: 'Africa/Maseru', utc_offset: '+2:00', currency: 'Lesotho Loti', currency_code: 'LSL', currency_symbol: 'L', sub_currency: 'Sente', service_tax: 15.00, is_active: true, display_order: 96 },
    { country_name: 'Liberia', country_code: 'LR', iso_code_2: 'LR', iso_code_3: 'LBR', phone_code: '+231', abbreviation: 'LBR', primary_timezone: 'Africa/Monrovia', utc_offset: '+0:00', currency: 'Liberian Dollar', currency_code: 'LRD', currency_symbol: '$', sub_currency: 'Cent', service_tax: 10.00, is_active: true, display_order: 97 },
    { country_name: 'Libya', country_code: 'LY', iso_code_2: 'LY', iso_code_3: 'LBY', phone_code: '+218', abbreviation: 'LBY', primary_timezone: 'Africa/Tripoli', utc_offset: '+2:00', currency: 'Libyan Dinar', currency_code: 'LYD', currency_symbol: 'ل.د', sub_currency: 'Dirham', service_tax: 0.00, is_active: true, display_order: 98 },
    { country_name: 'Liechtenstein', country_code: 'LI', iso_code_2: 'LI', iso_code_3: 'LIE', phone_code: '+423', abbreviation: 'LIE', primary_timezone: 'Europe/Vaduz', utc_offset: '+1:00', currency: 'Swiss Franc', currency_code: 'CHF', currency_symbol: 'Fr', sub_currency: 'Rappen', service_tax: 7.70, is_active: true, display_order: 99 },
    { country_name: 'Lithuania', country_code: 'LT', iso_code_2: 'LT', iso_code_3: 'LTU', phone_code: '+370', abbreviation: 'LTU', primary_timezone: 'Europe/Vilnius', utc_offset: '+2:00', currency: 'Euro', currency_code: 'EUR', currency_symbol: '€', sub_currency: 'Cent', service_tax: 21.00, is_active: true, display_order: 100 },
    { country_name: 'Luxembourg', country_code: 'LU', iso_code_2: 'LU', iso_code_3: 'LUX', phone_code: '+352', abbreviation: 'LUX', primary_timezone: 'Europe/Luxembourg', utc_offset: '+1:00', currency: 'Euro', currency_code: 'EUR', currency_symbol: '€', sub_currency: 'Cent', service_tax: 17.00, is_active: true, display_order: 101 },

    // M
    { country_name: 'Madagascar', country_code: 'MG', iso_code_2: 'MG', iso_code_3: 'MDG', phone_code: '+261', abbreviation: 'MDG', primary_timezone: 'Indian/Antananarivo', utc_offset: '+3:00', currency: 'Malagasy Ariary', currency_code: 'MGA', currency_symbol: 'Ar', sub_currency: 'Iraimbilanja', service_tax: 20.00, is_active: true, display_order: 102 },
    { country_name: 'Malawi', country_code: 'MW', iso_code_2: 'MW', iso_code_3: 'MWI', phone_code: '+265', abbreviation: 'MWI', primary_timezone: 'Africa/Blantyre', utc_offset: '+2:00', currency: 'Malawian Kwacha', currency_code: 'MWK', currency_symbol: 'MK', sub_currency: 'Tambala', service_tax: 16.50, is_active: true, display_order: 103 },
    { country_name: 'Malaysia', country_code: 'MY', iso_code_2: 'MY', iso_code_3: 'MYS', phone_code: '+60', abbreviation: 'MYS', primary_timezone: 'Asia/Kuala_Lumpur', utc_offset: '+8:00', currency: 'Malaysian Ringgit', currency_code: 'MYR', currency_symbol: 'RM', sub_currency: 'Sen', service_tax: 6.00, is_active: true, display_order: 104 },
    { country_name: 'Maldives', country_code: 'MV', iso_code_2: 'MV', iso_code_3: 'MDV', phone_code: '+960', abbreviation: 'MDV', primary_timezone: 'Indian/Maldives', utc_offset: '+5:00', currency: 'Maldivian Rufiyaa', currency_code: 'MVR', currency_symbol: 'ރ.', sub_currency: 'Laari', service_tax: 6.00, is_active: true, display_order: 105 },
    { country_name: 'Mali', country_code: 'ML', iso_code_2: 'ML', iso_code_3: 'MLI', phone_code: '+223', abbreviation: 'MLI', primary_timezone: 'Africa/Bamako', utc_offset: '+0:00', currency: 'West African CFA Franc', currency_code: 'XOF', currency_symbol: 'Fr', sub_currency: 'Centime', service_tax: 18.00, is_active: true, display_order: 106 },
    { country_name: 'Malta', country_code: 'MT', iso_code_2: 'MT', iso_code_3: 'MLT', phone_code: '+356', abbreviation: 'MLT', primary_timezone: 'Europe/Malta', utc_offset: '+1:00', currency: 'Euro', currency_code: 'EUR', currency_symbol: '€', sub_currency: 'Cent', service_tax: 18.00, is_active: true, display_order: 107 },
    { country_name: 'Marshall Islands', country_code: 'MH', iso_code_2: 'MH', iso_code_3: 'MHL', phone_code: '+692', abbreviation: 'MHL', primary_timezone: 'Pacific/Majuro', utc_offset: '+12:00', currency: 'United States Dollar', currency_code: 'USD', currency_symbol: '$', sub_currency: 'Cent', service_tax: 0.00, is_active: true, display_order: 108 },
    { country_name: 'Mauritania', country_code: 'MR', iso_code_2: 'MR', iso_code_3: 'MRT', phone_code: '+222', abbreviation: 'MRT', primary_timezone: 'Africa/Nouakchott', utc_offset: '+0:00', currency: 'Mauritanian Ouguiya', currency_code: 'MRU', currency_symbol: 'UM', sub_currency: 'Khoums', service_tax: 16.00, is_active: true, display_order: 109 },
    { country_name: 'Mauritius', country_code: 'MU', iso_code_2: 'MU', iso_code_3: 'MUS', phone_code: '+230', abbreviation: 'MUS', primary_timezone: 'Indian/Mauritius', utc_offset: '+4:00', currency: 'Mauritian Rupee', currency_code: 'MUR', currency_symbol: '₨', sub_currency: 'Cent', service_tax: 15.00, is_active: true, display_order: 110 },
    { country_name: 'Mexico', country_code: 'MX', iso_code_2: 'MX', iso_code_3: 'MEX', phone_code: '+52', abbreviation: 'MEX', primary_timezone: 'America/Mexico_City', utc_offset: '-6:00', currency: 'Mexican Peso', currency_code: 'MXN', currency_symbol: '$', sub_currency: 'Centavo', service_tax: 16.00, is_active: true, display_order: 111 },
    { country_name: 'Micronesia', country_code: 'FM', iso_code_2: 'FM', iso_code_3: 'FSM', phone_code: '+691', abbreviation: 'FSM', primary_timezone: 'Pacific/Pohnpei', utc_offset: '+11:00', currency: 'United States Dollar', currency_code: 'USD', currency_symbol: '$', sub_currency: 'Cent', service_tax: 0.00, is_active: true, display_order: 112 },
    { country_name: 'Moldova', country_code: 'MD', iso_code_2: 'MD', iso_code_3: 'MDA', phone_code: '+373', abbreviation: 'MDA', primary_timezone: 'Europe/Chisinau', utc_offset: '+2:00', currency: 'Moldovan Leu', currency_code: 'MDL', currency_symbol: 'L', sub_currency: 'Ban', service_tax: 20.00, is_active: true, display_order: 113 },
    { country_name: 'Monaco', country_code: 'MC', iso_code_2: 'MC', iso_code_3: 'MCO', phone_code: '+377', abbreviation: 'MCO', primary_timezone: 'Europe/Monaco', utc_offset: '+1:00', currency: 'Euro', currency_code: 'EUR', currency_symbol: '€', sub_currency: 'Cent', service_tax: 20.00, is_active: true, display_order: 114 },
    { country_name: 'Mongolia', country_code: 'MN', iso_code_2: 'MN', iso_code_3: 'MNG', phone_code: '+976', abbreviation: 'MNG', primary_timezone: 'Asia/Ulaanbaatar', utc_offset: '+8:00', currency: 'Mongolian Tögrög', currency_code: 'MNT', currency_symbol: '₮', sub_currency: 'Möngö', service_tax: 10.00, is_active: true, display_order: 115 },
    { country_name: 'Montenegro', country_code: 'ME', iso_code_2: 'ME', iso_code_3: 'MNE', phone_code: '+382', abbreviation: 'MNE', primary_timezone: 'Europe/Podgorica', utc_offset: '+1:00', currency: 'Euro', currency_code: 'EUR', currency_symbol: '€', sub_currency: 'Cent', service_tax: 21.00, is_active: true, display_order: 116 },
    { country_name: 'Morocco', country_code: 'MA', iso_code_2: 'MA', iso_code_3: 'MAR', phone_code: '+212', abbreviation: 'MAR', primary_timezone: 'Africa/Casablanca', utc_offset: '+1:00', currency: 'Moroccan Dirham', currency_code: 'MAD', currency_symbol: 'د.م.', sub_currency: 'Centime', service_tax: 20.00, is_active: true, display_order: 117 },
    { country_name: 'Mozambique', country_code: 'MZ', iso_code_2: 'MZ', iso_code_3: 'MOZ', phone_code: '+258', abbreviation: 'MOZ', primary_timezone: 'Africa/Maputo', utc_offset: '+2:00', currency: 'Mozambican Metical', currency_code: 'MZN', currency_symbol: 'MT', sub_currency: 'Centavo', service_tax: 17.00, is_active: true, display_order: 118 },
    { country_name: 'Myanmar', country_code: 'MM', iso_code_2: 'MM', iso_code_3: 'MMR', phone_code: '+95', abbreviation: 'MMR', primary_timezone: 'Asia/Yangon', utc_offset: '+6:30', currency: 'Myanmar Kyat', currency_code: 'MMK', currency_symbol: 'K', sub_currency: 'Pya', service_tax: 5.00, is_active: true, display_order: 119 },

    // N
    { country_name: 'Namibia', country_code: 'NA', iso_code_2: 'NA', iso_code_3: 'NAM', phone_code: '+264', abbreviation: 'NAM', primary_timezone: 'Africa/Windhoek', utc_offset: '+2:00', currency: 'Namibian Dollar', currency_code: 'NAD', currency_symbol: '$', sub_currency: 'Cent', service_tax: 15.00, is_active: true, display_order: 120 },
    { country_name: 'Nauru', country_code: 'NR', iso_code_2: 'NR', iso_code_3: 'NRU', phone_code: '+674', abbreviation: 'NRU', primary_timezone: 'Pacific/Nauru', utc_offset: '+12:00', currency: 'Australian Dollar', currency_code: 'AUD', currency_symbol: '$', sub_currency: 'Cent', service_tax: 0.00, is_active: true, display_order: 121 },
    { country_name: 'Nepal', country_code: 'NP', iso_code_2: 'NP', iso_code_3: 'NPL', phone_code: '+977', abbreviation: 'NPL', primary_timezone: 'Asia/Kathmandu', utc_offset: '+5:45', currency: 'Nepalese Rupee', currency_code: 'NPR', currency_symbol: '₨', sub_currency: 'Paisa', service_tax: 13.00, is_active: true, display_order: 122 },
    { country_name: 'Netherlands', country_code: 'NL', iso_code_2: 'NL', iso_code_3: 'NLD', phone_code: '+31', abbreviation: 'NLD', primary_timezone: 'Europe/Amsterdam', utc_offset: '+1:00', currency: 'Euro', currency_code: 'EUR', currency_symbol: '€', sub_currency: 'Cent', service_tax: 21.00, is_active: true, display_order: 123 },
    { country_name: 'New Zealand', country_code: 'NZ', iso_code_2: 'NZ', iso_code_3: 'NZL', phone_code: '+64', abbreviation: 'NZL', primary_timezone: 'Pacific/Auckland', utc_offset: '+12:00', currency: 'New Zealand Dollar', currency_code: 'NZD', currency_symbol: '$', sub_currency: 'Cent', service_tax: 15.00, is_active: true, display_order: 124 },
    { country_name: 'Nicaragua', country_code: 'NI', iso_code_2: 'NI', iso_code_3: 'NIC', phone_code: '+505', abbreviation: 'NIC', primary_timezone: 'America/Managua', utc_offset: '-6:00', currency: 'Nicaraguan Córdoba', currency_code: 'NIO', currency_symbol: 'C$', sub_currency: 'Centavo', service_tax: 15.00, is_active: true, display_order: 125 },
    { country_name: 'Niger', country_code: 'NE', iso_code_2: 'NE', iso_code_3: 'NER', phone_code: '+227', abbreviation: 'NER', primary_timezone: 'Africa/Niamey', utc_offset: '+1:00', currency: 'West African CFA Franc', currency_code: 'XOF', currency_symbol: 'Fr', sub_currency: 'Centime', service_tax: 19.00, is_active: true, display_order: 126 },
    { country_name: 'Nigeria', country_code: 'NG', iso_code_2: 'NG', iso_code_3: 'NGA', phone_code: '+234', abbreviation: 'NGA', primary_timezone: 'Africa/Lagos', utc_offset: '+1:00', currency: 'Nigerian Naira', currency_code: 'NGN', currency_symbol: '₦', sub_currency: 'Kobo', service_tax: 7.50, is_active: true, display_order: 127 },
    { country_name: 'North Korea', country_code: 'KP', iso_code_2: 'KP', iso_code_3: 'PRK', phone_code: '+850', abbreviation: 'PRK', primary_timezone: 'Asia/Pyongyang', utc_offset: '+9:00', currency: 'North Korean Won', currency_code: 'KPW', currency_symbol: '₩', sub_currency: 'Chon', service_tax: 0.00, is_active: true, display_order: 128 },
    { country_name: 'North Macedonia', country_code: 'MK', iso_code_2: 'MK', iso_code_3: 'MKD', phone_code: '+389', abbreviation: 'MKD', primary_timezone: 'Europe/Skopje', utc_offset: '+1:00', currency: 'Macedonian Denar', currency_code: 'MKD', currency_symbol: 'ден', sub_currency: 'Deni', service_tax: 18.00, is_active: true, display_order: 129 },
    { country_name: 'Norway', country_code: 'NO', iso_code_2: 'NO', iso_code_3: 'NOR', phone_code: '+47', abbreviation: 'NOR', primary_timezone: 'Europe/Oslo', utc_offset: '+1:00', currency: 'Norwegian Krone', currency_code: 'NOK', currency_symbol: 'kr', sub_currency: 'Øre', service_tax: 25.00, is_active: true, display_order: 130 },

    // O
    { country_name: 'Oman', country_code: 'OM', iso_code_2: 'OM', iso_code_3: 'OMN', phone_code: '+968', abbreviation: 'OMN', primary_timezone: 'Asia/Muscat', utc_offset: '+4:00', currency: 'Omani Rial', currency_code: 'OMR', currency_symbol: 'ر.ع.', sub_currency: 'Baisa', service_tax: 5.00, is_active: true, display_order: 131 },

    // P
    { country_name: 'Pakistan', country_code: 'PK', iso_code_2: 'PK', iso_code_3: 'PAK', phone_code: '+92', abbreviation: 'PAK', primary_timezone: 'Asia/Karachi', utc_offset: '+5:00', currency: 'Pakistani Rupee', currency_code: 'PKR', currency_symbol: '₨', sub_currency: 'Paisa', service_tax: 17.00, is_active: true, display_order: 132 },
    { country_name: 'Palau', country_code: 'PW', iso_code_2: 'PW', iso_code_3: 'PLW', phone_code: '+680', abbreviation: 'PLW', primary_timezone: 'Pacific/Palau', utc_offset: '+9:00', currency: 'United States Dollar', currency_code: 'USD', currency_symbol: '$', sub_currency: 'Cent', service_tax: 10.00, is_active: true, display_order: 133 },
    { country_name: 'Palestine', country_code: 'PS', iso_code_2: 'PS', iso_code_3: 'PSE', phone_code: '+970', abbreviation: 'PSE', primary_timezone: 'Asia/Gaza', utc_offset: '+2:00', currency: 'Israeli New Shekel', currency_code: 'ILS', currency_symbol: '₪', sub_currency: 'Agora', service_tax: 16.00, is_active: true, display_order: 134 },
    { country_name: 'Panama', country_code: 'PA', iso_code_2: 'PA', iso_code_3: 'PAN', phone_code: '+507', abbreviation: 'PAN', primary_timezone: 'America/Panama', utc_offset: '-5:00', currency: 'Panamanian Balboa', currency_code: 'PAB', currency_symbol: 'B/.', sub_currency: 'Centésimo', service_tax: 7.00, is_active: true, display_order: 135 },
    { country_name: 'Papua New Guinea', country_code: 'PG', iso_code_2: 'PG', iso_code_3: 'PNG', phone_code: '+675', abbreviation: 'PNG', primary_timezone: 'Pacific/Port_Moresby', utc_offset: '+10:00', currency: 'Papua New Guinean Kina', currency_code: 'PGK', currency_symbol: 'K', sub_currency: 'Toea', service_tax: 10.00, is_active: true, display_order: 136 },
    { country_name: 'Paraguay', country_code: 'PY', iso_code_2: 'PY', iso_code_3: 'PRY', phone_code: '+595', abbreviation: 'PRY', primary_timezone: 'America/Asuncion', utc_offset: '-4:00', currency: 'Paraguayan Guaraní', currency_code: 'PYG', currency_symbol: '₲', sub_currency: 'Céntimo', service_tax: 10.00, is_active: true, display_order: 137 },
    { country_name: 'Peru', country_code: 'PE', iso_code_2: 'PE', iso_code_3: 'PER', phone_code: '+51', abbreviation: 'PER', primary_timezone: 'America/Lima', utc_offset: '-5:00', currency: 'Peruvian Sol', currency_code: 'PEN', currency_symbol: 'S/', sub_currency: 'Céntimo', service_tax: 18.00, is_active: true, display_order: 138 },
    { country_name: 'Philippines', country_code: 'PH', iso_code_2: 'PH', iso_code_3: 'PHL', phone_code: '+63', abbreviation: 'PHL', primary_timezone: 'Asia/Manila', utc_offset: '+8:00', currency: 'Philippine Peso', currency_code: 'PHP', currency_symbol: '₱', sub_currency: 'Sentimo', service_tax: 12.00, is_active: true, display_order: 139 },
    { country_name: 'Poland', country_code: 'PL', iso_code_2: 'PL', iso_code_3: 'POL', phone_code: '+48', abbreviation: 'POL', primary_timezone: 'Europe/Warsaw', utc_offset: '+1:00', currency: 'Polish Złoty', currency_code: 'PLN', currency_symbol: 'zł', sub_currency: 'Grosz', service_tax: 23.00, is_active: true, display_order: 140 },
    { country_name: 'Portugal', country_code: 'PT', iso_code_2: 'PT', iso_code_3: 'PRT', phone_code: '+351', abbreviation: 'PRT', primary_timezone: 'Europe/Lisbon', utc_offset: '+0:00', currency: 'Euro', currency_code: 'EUR', currency_symbol: '€', sub_currency: 'Cent', service_tax: 23.00, is_active: true, display_order: 141 },

    // Q
    { country_name: 'Qatar', country_code: 'QA', iso_code_2: 'QA', iso_code_3: 'QAT', phone_code: '+974', abbreviation: 'QAT', primary_timezone: 'Asia/Qatar', utc_offset: '+3:00', currency: 'Qatari Riyal', currency_code: 'QAR', currency_symbol: 'ر.ق', sub_currency: 'Dirham', service_tax: 0.00, is_active: true, display_order: 142 },

    // R
    { country_name: 'Romania', country_code: 'RO', iso_code_2: 'RO', iso_code_3: 'ROU', phone_code: '+40', abbreviation: 'ROU', primary_timezone: 'Europe/Bucharest', utc_offset: '+2:00', currency: 'Romanian Leu', currency_code: 'RON', currency_symbol: 'lei', sub_currency: 'Ban', service_tax: 19.00, is_active: true, display_order: 143 },
    { country_name: 'Russia', country_code: 'RU', iso_code_2: 'RU', iso_code_3: 'RUS', phone_code: '+7', abbreviation: 'RUS', primary_timezone: 'Europe/Moscow', utc_offset: '+3:00', currency: 'Russian Ruble', currency_code: 'RUB', currency_symbol: '₽', sub_currency: 'Kopek', service_tax: 20.00, is_active: true, display_order: 144 },
    { country_name: 'Rwanda', country_code: 'RW', iso_code_2: 'RW', iso_code_3: 'RWA', phone_code: '+250', abbreviation: 'RWA', primary_timezone: 'Africa/Kigali', utc_offset: '+2:00', currency: 'Rwandan Franc', currency_code: 'RWF', currency_symbol: 'Fr', sub_currency: 'Centime', service_tax: 18.00, is_active: true, display_order: 145 },

    // S
    { country_name: 'Saint Kitts and Nevis', country_code: 'KN', iso_code_2: 'KN', iso_code_3: 'KNA', phone_code: '+1-869', abbreviation: 'KNA', primary_timezone: 'America/St_Kitts', utc_offset: '-4:00', currency: 'East Caribbean Dollar', currency_code: 'XCD', currency_symbol: '$', sub_currency: 'Cent', service_tax: 17.00, is_active: true, display_order: 146 },
    { country_name: 'Saint Lucia', country_code: 'LC', iso_code_2: 'LC', iso_code_3: 'LCA', phone_code: '+1-758', abbreviation: 'LCA', primary_timezone: 'America/St_Lucia', utc_offset: '-4:00', currency: 'East Caribbean Dollar', currency_code: 'XCD', currency_symbol: '$', sub_currency: 'Cent', service_tax: 12.50, is_active: true, display_order: 147 },
    { country_name: 'Saint Vincent and the Grenadines', country_code: 'VC', iso_code_2: 'VC', iso_code_3: 'VCT', phone_code: '+1-784', abbreviation: 'VCT', primary_timezone: 'America/St_Vincent', utc_offset: '-4:00', currency: 'East Caribbean Dollar', currency_code: 'XCD', currency_symbol: '$', sub_currency: 'Cent', service_tax: 16.00, is_active: true, display_order: 148 },
    { country_name: 'Samoa', country_code: 'WS', iso_code_2: 'WS', iso_code_3: 'WSM', phone_code: '+685', abbreviation: 'WSM', primary_timezone: 'Pacific/Apia', utc_offset: '+13:00', currency: 'Samoan Tala', currency_code: 'WST', currency_symbol: 'T', sub_currency: 'Sene', service_tax: 15.00, is_active: true, display_order: 149 },
    { country_name: 'San Marino', country_code: 'SM', iso_code_2: 'SM', iso_code_3: 'SMR', phone_code: '+378', abbreviation: 'SMR', primary_timezone: 'Europe/San_Marino', utc_offset: '+1:00', currency: 'Euro', currency_code: 'EUR', currency_symbol: '€', sub_currency: 'Cent', service_tax: 17.00, is_active: true, display_order: 150 },
    { country_name: 'Sao Tome and Principe', country_code: 'ST', iso_code_2: 'ST', iso_code_3: 'STP', phone_code: '+239', abbreviation: 'STP', primary_timezone: 'Africa/Sao_Tome', utc_offset: '+0:00', currency: 'São Tomé and Príncipe Dobra', currency_code: 'STN', currency_symbol: 'Db', sub_currency: 'Cêntimo', service_tax: 15.00, is_active: true, display_order: 151 },
    { country_name: 'Saudi Arabia', country_code: 'SA', iso_code_2: 'SA', iso_code_3: 'SAU', phone_code: '+966', abbreviation: 'SAU', primary_timezone: 'Asia/Riyadh', utc_offset: '+3:00', currency: 'Saudi Riyal', currency_code: 'SAR', currency_symbol: 'ر.س', sub_currency: 'Halala', service_tax: 15.00, is_active: true, display_order: 152 },
    { country_name: 'Senegal', country_code: 'SN', iso_code_2: 'SN', iso_code_3: 'SEN', phone_code: '+221', abbreviation: 'SEN', primary_timezone: 'Africa/Dakar', utc_offset: '+0:00', currency: 'West African CFA Franc', currency_code: 'XOF', currency_symbol: 'Fr', sub_currency: 'Centime', service_tax: 18.00, is_active: true, display_order: 153 },
    { country_name: 'Serbia', country_code: 'RS', iso_code_2: 'RS', iso_code_3: 'SRB', phone_code: '+381', abbreviation: 'SRB', primary_timezone: 'Europe/Belgrade', utc_offset: '+1:00', currency: 'Serbian Dinar', currency_code: 'RSD', currency_symbol: 'дин', sub_currency: 'Para', service_tax: 20.00, is_active: true, display_order: 154 },
    { country_name: 'Seychelles', country_code: 'SC', iso_code_2: 'SC', iso_code_3: 'SYC', phone_code: '+248', abbreviation: 'SYC', primary_timezone: 'Indian/Mahe', utc_offset: '+4:00', currency: 'Seychellois Rupee', currency_code: 'SCR', currency_symbol: '₨', sub_currency: 'Cent', service_tax: 15.00, is_active: true, display_order: 155 },
    { country_name: 'Sierra Leone', country_code: 'SL', iso_code_2: 'SL', iso_code_3: 'SLE', phone_code: '+232', abbreviation: 'SLE', primary_timezone: 'Africa/Freetown', utc_offset: '+0:00', currency: 'Sierra Leonean Leone', currency_code: 'SLL', currency_symbol: 'Le', sub_currency: 'Cent', service_tax: 15.00, is_active: true, display_order: 156 },
    { country_name: 'Singapore', country_code: 'SG', iso_code_2: 'SG', iso_code_3: 'SGP', phone_code: '+65', abbreviation: 'SGP', primary_timezone: 'Asia/Singapore', utc_offset: '+8:00', currency: 'Singapore Dollar', currency_code: 'SGD', currency_symbol: 'S$', sub_currency: 'Cent', service_tax: 7.00, is_active: true, display_order: 157 },
    { country_name: 'Slovakia', country_code: 'SK', iso_code_2: 'SK', iso_code_3: 'SVK', phone_code: '+421', abbreviation: 'SVK', primary_timezone: 'Europe/Bratislava', utc_offset: '+1:00', currency: 'Euro', currency_code: 'EUR', currency_symbol: '€', sub_currency: 'Cent', service_tax: 20.00, is_active: true, display_order: 158 },
    { country_name: 'Slovenia', country_code: 'SI', iso_code_2: 'SI', iso_code_3: 'SVN', phone_code: '+386', abbreviation: 'SVN', primary_timezone: 'Europe/Ljubljana', utc_offset: '+1:00', currency: 'Euro', currency_code: 'EUR', currency_symbol: '€', sub_currency: 'Cent', service_tax: 22.00, is_active: true, display_order: 159 },
    { country_name: 'Solomon Islands', country_code: 'SB', iso_code_2: 'SB', iso_code_3: 'SLB', phone_code: '+677', abbreviation: 'SLB', primary_timezone: 'Pacific/Guadalcanal', utc_offset: '+11:00', currency: 'Solomon Islands Dollar', currency_code: 'SBD', currency_symbol: '$', sub_currency: 'Cent', service_tax: 10.00, is_active: true, display_order: 160 },
    { country_name: 'Somalia', country_code: 'SO', iso_code_2: 'SO', iso_code_3: 'SOM', phone_code: '+252', abbreviation: 'SOM', primary_timezone: 'Africa/Mogadishu', utc_offset: '+3:00', currency: 'Somali Shilling', currency_code: 'SOS', currency_symbol: 'Sh', sub_currency: 'Cent', service_tax: 0.00, is_active: true, display_order: 161 },
    { country_name: 'South Africa', country_code: 'ZA', iso_code_2: 'ZA', iso_code_3: 'ZAF', phone_code: '+27', abbreviation: 'ZAF', primary_timezone: 'Africa/Johannesburg', utc_offset: '+2:00', currency: 'South African Rand', currency_code: 'ZAR', currency_symbol: 'R', sub_currency: 'Cent', service_tax: 15.00, is_active: true, display_order: 162 },
    { country_name: 'South Korea', country_code: 'KR', iso_code_2: 'KR', iso_code_3: 'KOR', phone_code: '+82', abbreviation: 'KOR', primary_timezone: 'Asia/Seoul', utc_offset: '+9:00', currency: 'South Korean Won', currency_code: 'KRW', currency_symbol: '₩', sub_currency: 'Jeon', service_tax: 10.00, is_active: true, display_order: 163 },
    { country_name: 'South Sudan', country_code: 'SS', iso_code_2: 'SS', iso_code_3: 'SSD', phone_code: '+211', abbreviation: 'SSD', primary_timezone: 'Africa/Juba', utc_offset: '+2:00', currency: 'South Sudanese Pound', currency_code: 'SSP', currency_symbol: '£', sub_currency: 'Piastre', service_tax: 0.00, is_active: true, display_order: 164 },
    { country_name: 'Spain', country_code: 'ES', iso_code_2: 'ES', iso_code_3: 'ESP', phone_code: '+34', abbreviation: 'ESP', primary_timezone: 'Europe/Madrid', utc_offset: '+1:00', currency: 'Euro', currency_code: 'EUR', currency_symbol: '€', sub_currency: 'Cent', service_tax: 21.00, is_active: true, display_order: 165 },
    { country_name: 'Sri Lanka', country_code: 'LK', iso_code_2: 'LK', iso_code_3: 'LKA', phone_code: '+94', abbreviation: 'LKA', primary_timezone: 'Asia/Colombo', utc_offset: '+5:30', currency: 'Sri Lankan Rupee', currency_code: 'LKR', currency_symbol: 'Rs', sub_currency: 'Cent', service_tax: 12.00, is_active: true, display_order: 166 },
    { country_name: 'Sudan', country_code: 'SD', iso_code_2: 'SD', iso_code_3: 'SDN', phone_code: '+249', abbreviation: 'SDN', primary_timezone: 'Africa/Khartoum', utc_offset: '+2:00', currency: 'Sudanese Pound', currency_code: 'SDG', currency_symbol: 'ج.س.', sub_currency: 'Piastre', service_tax: 17.00, is_active: true, display_order: 167 },
    { country_name: 'Suriname', country_code: 'SR', iso_code_2: 'SR', iso_code_3: 'SUR', phone_code: '+597', abbreviation: 'SUR', primary_timezone: 'America/Paramaribo', utc_offset: '-3:00', currency: 'Surinamese Dollar', currency_code: 'SRD', currency_symbol: '$', sub_currency: 'Cent', service_tax: 10.00, is_active: true, display_order: 168 },
    { country_name: 'Sweden', country_code: 'SE', iso_code_2: 'SE', iso_code_3: 'SWE', phone_code: '+46', abbreviation: 'SWE', primary_timezone: 'Europe/Stockholm', utc_offset: '+1:00', currency: 'Swedish Krona', currency_code: 'SEK', currency_symbol: 'kr', sub_currency: 'Öre', service_tax: 25.00, is_active: true, display_order: 169 },
    { country_name: 'Switzerland', country_code: 'CH', iso_code_2: 'CH', iso_code_3: 'CHE', phone_code: '+41', abbreviation: 'SUI', primary_timezone: 'Europe/Zurich', utc_offset: '+1:00', currency: 'Swiss Franc', currency_code: 'CHF', currency_symbol: 'Fr', sub_currency: 'Rappen', service_tax: 7.70, is_active: true, display_order: 170 },
    { country_name: 'Syria', country_code: 'SY', iso_code_2: 'SY', iso_code_3: 'SYR', phone_code: '+963', abbreviation: 'SYR', primary_timezone: 'Asia/Damascus', utc_offset: '+2:00', currency: 'Syrian Pound', currency_code: 'SYP', currency_symbol: '£S', sub_currency: 'Piastre', service_tax: 0.00, is_active: true, display_order: 171 },

    // T
    { country_name: 'Taiwan', country_code: 'TW', iso_code_2: 'TW', iso_code_3: 'TWN', phone_code: '+886', abbreviation: 'TWN', primary_timezone: 'Asia/Taipei', utc_offset: '+8:00', currency: 'New Taiwan Dollar', currency_code: 'TWD', currency_symbol: 'NT$', sub_currency: 'Cent', service_tax: 5.00, is_active: true, display_order: 172 },
    { country_name: 'Tajikistan', country_code: 'TJ', iso_code_2: 'TJ', iso_code_3: 'TJK', phone_code: '+992', abbreviation: 'TJK', primary_timezone: 'Asia/Dushanbe', utc_offset: '+5:00', currency: 'Tajikistani Somoni', currency_code: 'TJS', currency_symbol: 'ЅМ', sub_currency: 'Diram', service_tax: 18.00, is_active: true, display_order: 173 },
    { country_name: 'Tanzania', country_code: 'TZ', iso_code_2: 'TZ', iso_code_3: 'TZA', phone_code: '+255', abbreviation: 'TZA', primary_timezone: 'Africa/Dar_es_Salaam', utc_offset: '+3:00', currency: 'Tanzanian Shilling', currency_code: 'TZS', currency_symbol: 'Sh', sub_currency: 'Cent', service_tax: 18.00, is_active: true, display_order: 174 },
    { country_name: 'Thailand', country_code: 'TH', iso_code_2: 'TH', iso_code_3: 'THA', phone_code: '+66', abbreviation: 'THA', primary_timezone: 'Asia/Bangkok', utc_offset: '+7:00', currency: 'Thai Baht', currency_code: 'THB', currency_symbol: '฿', sub_currency: 'Satang', service_tax: 7.00, is_active: true, display_order: 175 },
    { country_name: 'Togo', country_code: 'TG', iso_code_2: 'TG', iso_code_3: 'TGO', phone_code: '+228', abbreviation: 'TGO', primary_timezone: 'Africa/Lome', utc_offset: '+0:00', currency: 'West African CFA Franc', currency_code: 'XOF', currency_symbol: 'Fr', sub_currency: 'Centime', service_tax: 18.00, is_active: true, display_order: 176 },
    { country_name: 'Tonga', country_code: 'TO', iso_code_2: 'TO', iso_code_3: 'TON', phone_code: '+676', abbreviation: 'TON', primary_timezone: 'Pacific/Tongatapu', utc_offset: '+13:00', currency: 'Tongan Paʻanga', currency_code: 'TOP', currency_symbol: 'T$', sub_currency: 'Seniti', service_tax: 15.00, is_active: true, display_order: 177 },
    { country_name: 'Trinidad and Tobago', country_code: 'TT', iso_code_2: 'TT', iso_code_3: 'TTO', phone_code: '+1-868', abbreviation: 'TTO', primary_timezone: 'America/Port_of_Spain', utc_offset: '-4:00', currency: 'Trinidad and Tobago Dollar', currency_code: 'TTD', currency_symbol: '$', sub_currency: 'Cent', service_tax: 12.50, is_active: true, display_order: 178 },
    { country_name: 'Tunisia', country_code: 'TN', iso_code_2: 'TN', iso_code_3: 'TUN', phone_code: '+216', abbreviation: 'TUN', primary_timezone: 'Africa/Tunis', utc_offset: '+1:00', currency: 'Tunisian Dinar', currency_code: 'TND', currency_symbol: 'د.ت', sub_currency: 'Millime', service_tax: 19.00, is_active: true, display_order: 179 },
    { country_name: 'Turkey', country_code: 'TR', iso_code_2: 'TR', iso_code_3: 'TUR', phone_code: '+90', abbreviation: 'TUR', primary_timezone: 'Europe/Istanbul', utc_offset: '+3:00', currency: 'Turkish Lira', currency_code: 'TRY', currency_symbol: '₺', sub_currency: 'Kuruş', service_tax: 18.00, is_active: true, display_order: 180 },
    { country_name: 'Turkmenistan', country_code: 'TM', iso_code_2: 'TM', iso_code_3: 'TKM', phone_code: '+993', abbreviation: 'TKM', primary_timezone: 'Asia/Ashgabat', utc_offset: '+5:00', currency: 'Turkmenistan Manat', currency_code: 'TMT', currency_symbol: 'm', sub_currency: 'Tenge', service_tax: 15.00, is_active: true, display_order: 181 },
    { country_name: 'Tuvalu', country_code: 'TV', iso_code_2: 'TV', iso_code_3: 'TUV', phone_code: '+688', abbreviation: 'TUV', primary_timezone: 'Pacific/Funafuti', utc_offset: '+12:00', currency: 'Australian Dollar', currency_code: 'AUD', currency_symbol: '$', sub_currency: 'Cent', service_tax: 0.00, is_active: true, display_order: 182 },

    // U
    { country_name: 'Uganda', country_code: 'UG', iso_code_2: 'UG', iso_code_3: 'UGA', phone_code: '+256', abbreviation: 'UGA', primary_timezone: 'Africa/Kampala', utc_offset: '+3:00', currency: 'Ugandan Shilling', currency_code: 'UGX', currency_symbol: 'Sh', sub_currency: 'Cent', service_tax: 18.00, is_active: true, display_order: 183 },
    { country_name: 'Ukraine', country_code: 'UA', iso_code_2: 'UA', iso_code_3: 'UKR', phone_code: '+380', abbreviation: 'UKR', primary_timezone: 'Europe/Kiev', utc_offset: '+2:00', currency: 'Ukrainian Hryvnia', currency_code: 'UAH', currency_symbol: '₴', sub_currency: 'Kopiyka', service_tax: 20.00, is_active: true, display_order: 184 },
    { country_name: 'United Arab Emirates', country_code: 'AE', iso_code_2: 'AE', iso_code_3: 'ARE', phone_code: '+971', abbreviation: 'UAE', primary_timezone: 'Asia/Dubai', utc_offset: '+4:00', currency: 'UAE Dirham', currency_code: 'AED', currency_symbol: 'د.إ', sub_currency: 'Fils', service_tax: 5.00, is_active: true, display_order: 185 },
    { country_name: 'United Kingdom', country_code: 'GB', iso_code_2: 'GB', iso_code_3: 'GBR', phone_code: '+44', abbreviation: 'UK', primary_timezone: 'Europe/London', utc_offset: '+0:00', currency: 'British Pound', currency_code: 'GBP', currency_symbol: '£', sub_currency: 'Penny', service_tax: 20.00, is_active: true, display_order: 186 },
    { country_name: 'United States', country_code: 'US', iso_code_2: 'US', iso_code_3: 'USA', phone_code: '+1', abbreviation: 'USA', primary_timezone: 'America/New_York', utc_offset: '-5:00', currency: 'US Dollar', currency_code: 'USD', currency_symbol: '$', sub_currency: 'Cent', service_tax: 0.00, is_active: true, display_order: 187 },
    { country_name: 'Uruguay', country_code: 'UY', iso_code_2: 'UY', iso_code_3: 'URY', phone_code: '+598', abbreviation: 'URY', primary_timezone: 'America/Montevideo', utc_offset: '-3:00', currency: 'Uruguayan Peso', currency_code: 'UYU', currency_symbol: '$', sub_currency: 'Centésimo', service_tax: 22.00, is_active: true, display_order: 188 },
    { country_name: 'Uzbekistan', country_code: 'UZ', iso_code_2: 'UZ', iso_code_3: 'UZB', phone_code: '+998', abbreviation: 'UZB', primary_timezone: 'Asia/Tashkent', utc_offset: '+5:00', currency: 'Uzbekistani Som', currency_code: 'UZS', currency_symbol: "so'm", sub_currency: 'Tiyin', service_tax: 12.00, is_active: true, display_order: 189 },

    // V
    { country_name: 'Vanuatu', country_code: 'VU', iso_code_2: 'VU', iso_code_3: 'VUT', phone_code: '+678', abbreviation: 'VUT', primary_timezone: 'Pacific/Efate', utc_offset: '+11:00', currency: 'Vanuatu Vatu', currency_code: 'VUV', currency_symbol: 'Vt', sub_currency: '', service_tax: 15.00, is_active: true, display_order: 190 },
    { country_name: 'Vatican City', country_code: 'VA', iso_code_2: 'VA', iso_code_3: 'VAT', phone_code: '+39', abbreviation: 'VAT', primary_timezone: 'Europe/Vatican', utc_offset: '+1:00', currency: 'Euro', currency_code: 'EUR', currency_symbol: '€', sub_currency: 'Cent', service_tax: 0.00, is_active: true, display_order: 191 },
    { country_name: 'Venezuela', country_code: 'VE', iso_code_2: 'VE', iso_code_3: 'VEN', phone_code: '+58', abbreviation: 'VEN', primary_timezone: 'America/Caracas', utc_offset: '-4:00', currency: 'Venezuelan Bolívar', currency_code: 'VES', currency_symbol: 'Bs.', sub_currency: 'Céntimo', service_tax: 16.00, is_active: true, display_order: 192 },
    { country_name: 'Vietnam', country_code: 'VN', iso_code_2: 'VN', iso_code_3: 'VNM', phone_code: '+84', abbreviation: 'VNM', primary_timezone: 'Asia/Ho_Chi_Minh', utc_offset: '+7:00', currency: 'Vietnamese Dong', currency_code: 'VND', currency_symbol: '₫', sub_currency: 'Xu', service_tax: 10.00, is_active: true, display_order: 193 },

    // Y
    { country_name: 'Yemen', country_code: 'YE', iso_code_2: 'YE', iso_code_3: 'YEM', phone_code: '+967', abbreviation: 'YEM', primary_timezone: 'Asia/Aden', utc_offset: '+3:00', currency: 'Yemeni Rial', currency_code: 'YER', currency_symbol: '﷼', sub_currency: 'Fils', service_tax: 5.00, is_active: true, display_order: 194 },

    // Z
    { country_name: 'Zambia', country_code: 'ZM', iso_code_2: 'ZM', iso_code_3: 'ZMB', phone_code: '+260', abbreviation: 'ZMB', primary_timezone: 'Africa/Lusaka', utc_offset: '+2:00', currency: 'Zambian Kwacha', currency_code: 'ZMW', currency_symbol: 'ZK', sub_currency: 'Ngwee', service_tax: 16.00, is_active: true, display_order: 195 },
    { country_name: 'Zimbabwe', country_code: 'ZW', iso_code_2: 'ZW', iso_code_3: 'ZWE', phone_code: '+263', abbreviation: 'ZWE', primary_timezone: 'Africa/Harare', utc_offset: '+2:00', currency: 'Zimbabwean Dollar', currency_code: 'ZWL', currency_symbol: '$', sub_currency: 'Cent', service_tax: 14.50, is_active: true, display_order: 196 }
];

/**
 * Seed Countries
 */
const seedCountries = async () => {
    try {
        console.log('🌍 Starting country seeder...');

        // Sync the model to create table if it doesn't exist
        await HrmsCountryMaster.sync({ alter: true });
        console.log('✓ Country table synced');

        // Insert countries using bulkCreate with updateOnDuplicate
        const result = await HrmsCountryMaster.bulkCreate(countries, {
            updateOnDuplicate: ['country_name', 'phone_code', 'abbreviation', 'primary_timezone', 'utc_offset', 'currency', 'currency_code', 'currency_symbol', 'sub_currency', 'service_tax', 'is_active', 'display_order', 'updated_at']
        });

        console.log(`✓ ${result.length} countries seeded successfully`);
        console.log('✓ Country seeder completed');

        return result;
    } catch (error) {
        console.error('✗ Country seeder error:', error.message);
        throw error;
    }
};

// Run seeder if called directly
if (require.main === module) {
    seedCountries()
        .then(() => {
            console.log('✓ Seeding completed successfully');
            process.exit(0);
        })
        .catch((error) => {
            console.error('✗ Seeding failed:', error);
            process.exit(1);
        });
}

module.exports = { seedCountries };
